onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider aes_top
add wave -noupdate /tb/u_aes_top/clk
add wave -noupdate /tb/u_aes_top/rstn
add wave -noupdate /tb/u_aes_top/intr
add wave -noupdate /tb/u_aes_top/psel
add wave -noupdate /tb/u_aes_top/penable
add wave -noupdate /tb/u_aes_top/paddr
add wave -noupdate /tb/u_aes_top/pwrite
add wave -noupdate /tb/u_aes_top/pwdata
add wave -noupdate /tb/u_aes_top/pready
add wave -noupdate /tb/u_aes_top/prdata
add wave -noupdate /tb/u_aes_top/arid
add wave -noupdate /tb/u_aes_top/araddr
add wave -noupdate /tb/u_aes_top/arlen
add wave -noupdate /tb/u_aes_top/arsize
add wave -noupdate /tb/u_aes_top/arburst
add wave -noupdate /tb/u_aes_top/arlock
add wave -noupdate /tb/u_aes_top/arcache
add wave -noupdate /tb/u_aes_top/arprot
add wave -noupdate /tb/u_aes_top/arvalid
add wave -noupdate /tb/u_aes_top/arready
add wave -noupdate /tb/u_aes_top/rid
add wave -noupdate /tb/u_aes_top/rdata
add wave -noupdate /tb/u_aes_top/rresp
add wave -noupdate /tb/u_aes_top/rlast
add wave -noupdate /tb/u_aes_top/rvalid
add wave -noupdate /tb/u_aes_top/rready
add wave -noupdate /tb/u_aes_top/awid
add wave -noupdate /tb/u_aes_top/awaddr
add wave -noupdate /tb/u_aes_top/awlen
add wave -noupdate /tb/u_aes_top/awsize
add wave -noupdate /tb/u_aes_top/awburst
add wave -noupdate /tb/u_aes_top/awlock
add wave -noupdate /tb/u_aes_top/awcache
add wave -noupdate /tb/u_aes_top/awprot
add wave -noupdate /tb/u_aes_top/awvalid
add wave -noupdate /tb/u_aes_top/awready
add wave -noupdate /tb/u_aes_top/wid
add wave -noupdate /tb/u_aes_top/wdata
add wave -noupdate /tb/u_aes_top/wstrb
add wave -noupdate /tb/u_aes_top/wlast
add wave -noupdate /tb/u_aes_top/wvalid
add wave -noupdate /tb/u_aes_top/wready
add wave -noupdate /tb/u_aes_top/bid
add wave -noupdate /tb/u_aes_top/bresp
add wave -noupdate /tb/u_aes_top/bvalid
add wave -noupdate /tb/u_aes_top/bready
add wave -noupdate -divider cfg
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_key_gen
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_blk_sof
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_blk_base
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_blk_len
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_code_base
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_enc_dec
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_key_len
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_blk_mode
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_key
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_iv
add wave -noupdate /tb/u_aes_top/u_aes_cfg/set_blk_end
add wave -noupdate /tb/u_aes_top/u_aes_cfg/intr
add wave -noupdate /tb/u_aes_top/u_aes_cfg/key
add wave -noupdate /tb/u_aes_top/u_aes_cfg/iv
add wave -noupdate -divider axir
add wave -noupdate /tb/u_aes_top/u_aes_axir/clk
add wave -noupdate /tb/u_aes_top/u_aes_axir/cfg_blk_sof
add wave -noupdate /tb/u_aes_top/u_aes_axir/cfg_blk_base
add wave -noupdate /tb/u_aes_top/u_aes_axir/cfg_blk_len
add wave -noupdate /tb/u_aes_top/u_aes_axir/ibuf_rptr
add wave -noupdate /tb/u_aes_top/u_aes_axir/ibuf_wptr
add wave -noupdate /tb/u_aes_top/u_aes_axir/axi_sta
add wave -noupdate /tb/u_aes_top/u_aes_axir/axi_addr
add wave -noupdate /tb/u_aes_top/u_aes_axir/blk_len
add wave -noupdate /tb/u_aes_top/u_aes_axir/araddr
add wave -noupdate /tb/u_aes_top/u_aes_axir/arvalid
add wave -noupdate /tb/u_aes_top/u_aes_axir/arready
add wave -noupdate /tb/u_aes_top/u_aes_axir/rvalid
add wave -noupdate /tb/u_aes_top/u_aes_axir/rready
add wave -noupdate /tb/u_aes_top/u_aes_axir/rlast
add wave -noupdate /tb/u_aes_top/u_aes_axir/rdata
add wave -noupdate -divider axiw
add wave -noupdate /tb/u_aes_top/u_aes_axiw/cfg_blk_sof
add wave -noupdate /tb/u_aes_top/u_aes_axiw/cfg_code_base
add wave -noupdate /tb/u_aes_top/u_aes_axiw/obuf_rd
add wave -noupdate /tb/u_aes_top/u_aes_axiw/obuf_raddr
add wave -noupdate /tb/u_aes_top/u_aes_axiw/obuf_rdata
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/obuf_wptr
add wave -noupdate /tb/u_aes_top/u_aes_axiw/obuf_rptr
add wave -noupdate /tb/u_aes_top/u_aes_axiw/obuf_empty
add wave -noupdate /tb/u_aes_top/u_aes_axiw/axi_sta
add wave -noupdate /tb/u_aes_top/u_aes_axiw/awvalid
add wave -noupdate /tb/u_aes_top/u_aes_axiw/awready
add wave -noupdate /tb/u_aes_top/u_aes_axiw/wdata
add wave -noupdate /tb/u_aes_top/u_aes_axiw/wlast
add wave -noupdate /tb/u_aes_top/u_aes_axiw/wvalid
add wave -noupdate /tb/u_aes_top/u_aes_axiw/wready
add wave -noupdate -divider flow_ctrl
add wave -noupdate /tb/u_aes_top/u_aes_axiw/cfg_blk_sof
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/sta
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/ibuf_wptr
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/ibuf_rptr
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/obuf_wptr
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/obuf_rptr
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/set_blk_end
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/key_ready
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/enc_sof
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/enc_blk_end
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/enc_text
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/enc_ready
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/enc_code
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/first_blk
add wave -noupdate -divider enc_core
add wave -noupdate /tb/u_aes_top/u_aes_core/clk
add wave -noupdate /tb/u_aes_top/u_aes_core/encdec
add wave -noupdate /tb/u_aes_top/u_aes_core/init
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/key_ready
add wave -noupdate -color Violet /tb/u_aes_top/u_aes_core/next
add wave -noupdate /tb/u_aes_top/u_aes_core/key
add wave -noupdate /tb/u_aes_top/u_aes_core/block
add wave -noupdate /tb/u_aes_top/u_aes_core/result_valid
add wave -noupdate /tb/u_aes_top/u_aes_core/result
add wave -noupdate -divider keymem
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/clk
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/init
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/key
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/key_mem_ctrl_reg
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/round_ctr_reg
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/rcon_next
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/rcon_new
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/round_key_gen/rconw
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/prev_key0_we
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/prev_key0_reg
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/prev_key1_we
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/prev_key1_reg
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/key_mem_we
add wave -noupdate /tb/u_aes_top/u_aes_core/keymem/key_mem_new
add wave -noupdate -divider encipher
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/next
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/enc_ctrl_reg
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/round_ctr_reg
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/encipher_ctrl/num_rounds
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/block
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/new_block
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/ready
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/block_w0_we
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/block_w1_we
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/block_w2_we
add wave -noupdate /tb/u_aes_top/u_aes_core/enc_block/block_w3_we
add wave -noupdate /tb/u_aes_top/u_aes_cfg/cfg_blk_sof
add wave -noupdate /tb/u_aes_top/u_aes_cfg/set_blk_end
add wave -noupdate /tb/u_aes_top/u_aes_core/dec_cbc_mem
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/first_blk
add wave -noupdate /tb/u_aes_top/u_aes_core/clk
add wave -noupdate /tb/u_aes_top/u_aes_core/next
add wave -noupdate /tb/u_aes_top/u_aes_core/dec_next
add wave -noupdate /tb/u_aes_top/u_aes_core/dec_ready
add wave -noupdate /tb/u_aes_top/u_aes_core/result_valid
add wave -noupdate /tb/u_aes_top/u_aes_flow_ctrl/sta
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2165000 ps} 0} {{Cursor 2} {1325000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 248
configure wave -valuecolwidth 168
configure wave -justifyvalue left
configure wave -signalnamewidth 2
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {22619 ns} {23636900 ps}
